In [1]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array
from matplotlib import pyplot # to visulaise data
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
train_data=pd.read_csv("Train.csv")
train_data.head(5)

variable_0  variable_1  variable_2  variable_3  variable_4  variable_5  \
0    1.616623   -0.909091         3.0   -0.041629    0.284188    0.166667   
1   -0.029310    1.500000         0.0    0.551353   -0.515812    0.166667   
2    1.598362    0.227273         0.0   -0.280171   -0.385897   -1.166667   
3    0.355677    0.954545         0.0   -0.101158    0.158718   -0.333333   
4   -0.291358    0.590909         0.0   -0.299727    0.696838    0.000000   

   variable_6  variable_7  variable_8  variable_9  class_col  
0         0.0         0.0         1.0         2.0        0.0  
1         0.0        -0.5         0.0         0.0        0.0  
2         0.0        -0.5         0.0         0.0        0.0  
3         0.0         0.0         0.0         0.0        0.0  
4         0.0         0.5         0.0         0.0        0.0

In [3]:
X = train_data.iloc[0:100000, :-1].values
X

array([[ 1.61662315, -0.90909091,  3.        , ...,  0.        ,
         1.        ,  2.        ],
       [-0.02931037,  1.5       ,  0.        , ..., -0.5       ,
         0.        ,  0.        ],
       [ 1.59836175,  0.22727273,  0.        , ..., -0.5       ,
         0.        ,  0.        ],
       ...,
       [ 0.12700466,  0.27272727,  0.        , ...,  0.        ,
         0.        ,  3.        ],
       [ 0.01279284, -0.72727273,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.2971423 ,  0.77272727,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [4]:
Y = train_data.iloc[0:100000, -1].values
Y

array([0., 0., 0., ..., 0., 0., 0.])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [12]:
Higher = train_data[train_data.class_col == 1]
Lower = train_data[train_data.class_col == 0]

In [14]:
print(Higher.shape)
print(Lower.shape)

(6651, 11)
(93349, 11)


In [130]:
Lower_new = Lower.sample(n=60000)


In [131]:
new_dataset = pd.concat([Higher, Lower_new], axis=0)

In [132]:
new_dataset['class_col'].value_counts()

0.0    60000
1.0     6651
Name: class_col, dtype: int64

In [133]:
new_dataset

variable_0  variable_1  variable_2   variable_3  variable_4  \
13       1.598362   -0.818182         0.0    -0.523490   -0.180769   
15       1.398450   -0.681818         4.0    -0.076944   -0.061111   
16       0.186068    0.000000         0.0  1981.640568   -0.744872   
44       1.319824    0.454545         2.0    -0.210600    0.317692   
59      -0.166838   -0.818182         0.0  5953.192307   -0.744872   
...           ...         ...         ...          ...         ...   
84141    1.598362   -0.772727         1.0   111.996161   -0.744872   
92015    0.094167    1.045455         0.0    -0.352275    0.529487   
19236   -0.288767    0.090909         0.0    -0.257364    0.537179   
356      0.374989   -0.272727         0.0  2624.330833   -0.744701   
82951    1.199740    0.181818         0.0  2578.888087   -0.744872   

       variable_5  variable_6  variable_7  variable_8  variable_9  class_col  
13      -1.333333         0.0        -0.5         0.0         4.0        1.0  
15      -0.333333         3.0        -0.5         2.0         3.0        1.0  
16       0.333333         0.0         0.0         0.0         0.0        1.0  
44       0.166667         0.0        -0.5         1.0         2.0        1.0  
59      -0.500000         0.0         1.0         0.0         0.0        1.0  
...           ...         ...         ...         ...         ...        ...  
84141   -0.833333         0.0        -0.5         0.0         0.0        0.0  
92015    0.166667         0.0         0.0         0.0         0.0        0.0  
19236   -0.166667         0.0         0.5         0.0         2.0        0.0  
356     -0.166667         0.0         0.5         0.0         0.0        0.0  
82951    0.500000         0.0        -0.5         0.0         0.0        0.0  

[66651 rows x 11 columns]

In [134]:
new_dataset.head()

variable_0  variable_1  variable_2   variable_3  variable_4  variable_5  \
13    1.598362   -0.818182         0.0    -0.523490   -0.180769   -1.333333   
15    1.398450   -0.681818         4.0    -0.076944   -0.061111   -0.333333   
16    0.186068    0.000000         0.0  1981.640568   -0.744872    0.333333   
44    1.319824    0.454545         2.0    -0.210600    0.317692    0.166667   
59   -0.166838   -0.818182         0.0  5953.192307   -0.744872   -0.500000   

    variable_6  variable_7  variable_8  variable_9  class_col  
13         0.0        -0.5         0.0         4.0        1.0  
15         3.0        -0.5         2.0         3.0        1.0  
16         0.0         0.0         0.0         0.0        1.0  
44         0.0        -0.5         1.0         2.0        1.0  
59         0.0         1.0         0.0         0.0        1.0

In [135]:
new_dataset.tail()

variable_0  variable_1  variable_2   variable_3  variable_4  \
84141    1.598362   -0.772727         1.0   111.996161   -0.744872   
92015    0.094167    1.045455         0.0    -0.352275    0.529487   
19236   -0.288767    0.090909         0.0    -0.257364    0.537179   
356      0.374989   -0.272727         0.0  2624.330833   -0.744701   
82951    1.199740    0.181818         0.0  2578.888087   -0.744872   

       variable_5  variable_6  variable_7  variable_8  variable_9  class_col  
84141   -0.833333         0.0        -0.5         0.0         0.0        0.0  
92015    0.166667         0.0         0.0         0.0         0.0        0.0  
19236   -0.166667         0.0         0.5         0.0         2.0        0.0  
356     -0.166667         0.0         0.5         0.0         0.0        0.0  
82951    0.500000         0.0        -0.5         0.0         0.0        0.0

In [136]:
X = new_dataset.iloc[:, :-1].values
X

array([[ 1.59836175, -0.81818182,  0.        , ..., -0.5       ,
         0.        ,  4.        ],
       [ 1.39844983, -0.68181818,  4.        , ..., -0.5       ,
         2.        ,  3.        ],
       [ 0.18606751,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.28876667,  0.09090909,  0.        , ...,  0.5       ,
         0.        ,  2.        ],
       [ 0.37498896, -0.27272727,  0.        , ...,  0.5       ,
         0.        ,  0.        ],
       [ 1.1997399 ,  0.18181818,  0.        , ..., -0.5       ,
         0.        ,  0.        ]])

In [137]:
Y = new_dataset.iloc[:, -1].values
Y

array([1., 1., 1., ..., 0., 0., 0.])

In [138]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [139]:
print(X.shape, X_train.shape, X_test.shape)

(66651, 10) (53320, 10) (13331, 10)


In [140]:

model = LogisticRegression(max_iter=450)

In [141]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=450)

In [142]:
# accuracy on training data
Y_pred = model.predict(X_test)

In [143]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred )

print("Confusion Matrix: ")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(Y_test, Y_pred)*100))

Confusion Matrix: 
[[11959    42]
 [ 1246    84]]
Accuracy of the Model: 90.33830920411073%


In [144]:
test_data=pd.read_csv("Eval.csv")
X_new = test_data.iloc[:,:].values

In [145]:
Y_new=model.predict(X_new)
print(Y_new)

[0. 0. 0. ... 0. 0. 0.]


In [146]:
num_ones = np.count_nonzero(Y_new)
num_zeros = len(Y_new)-num_ones

In [147]:
print("No-of zeros=", num_zeros)
print("No-of ones = ", num_ones)

No-of zeros= 49655
No-of ones =  345
